<script setup>
const props = defineProps({ model: { type: Object, required: true } })
const { detailDialog, qualityChecks, quantityEvents, growthSamples, batchHistoryLoading, growthDialog, growthForm, selectedBatch, emptyGrowthForm, statusNames, checkTypeOptions, resultNames, reviewNames, speciesNames, broodstockNames, formatDate, formatTimestamp, formatQuantity, openQualityHistory, openQuantityForm, quantityEventNames, quantityEventDelta, tanks, loading, quantityDialog, quantitySaving, quantityForm, form, canManage, saveQuantityEvent, growthSaving, saveGrowthSample } = props.model
</script>

<template>
<v-dialog v-model="detailDialog" max-width="900" scrollable>
      <v-card class="dialog-card"><span class="eyebrow">HỒ SƠ LÔ GIỐNG</span><template v-if="selectedBatch"><h2>{{ selectedBatch.batchCode }}</h2><p class="detail-subtitle">{{ speciesNames[selectedBatch.species] || selectedBatch.species }} · {{ selectedBatch.developmentStage }}</p>
        <dl class="detail-grid"><div><dt>Trạng thái</dt><dd><span class="status-tag" :class="`status-${selectedBatch.status}`">{{ statusNames[selectedBatch.status] }}</span></dd></div><div><dt>Ao/bể</dt><dd>{{ selectedBatch.tank?.code }} · {{ selectedBatch.tank?.name }}</dd></div><div><dt>Khu vực</dt><dd>{{ selectedBatch.tank?.area?.name || 'Toàn trại' }}</dd></div><div><dt>Nhà cung cấp</dt><dd>{{ selectedBatch.supplier?.name || selectedBatch.source || '—' }}</dd></div><div><dt>Mã lô nhà cung cấp</dt><dd>{{ selectedBatch.supplierLotCode }}</dd></div><div><dt>Nguồn</dt><dd>{{ selectedBatch.source }}</dd></div><div><dt>Số lượng ban đầu</dt><dd>{{ formatQuantity(selectedBatch.initialQuantity) }}</dd></div><div><dt>Số lượng hiện tại</dt><dd>{{ formatQuantity(selectedBatch.currentEstimatedQuantity) }}</dd></div><div><dt>Theo chứng từ</dt><dd>{{ formatQuantity(selectedBatch.documentedQuantity) }}</dd></div><div><dt>Ngày thả</dt><dd>{{ formatDate(selectedBatch.stockedDate) }}</dd></div><div><dt>Dự kiến bán</dt><dd>{{ formatDate(selectedBatch.expectedSaleDate) }}</dd></div><div><dt>Tôm bố mẹ</dt><dd>{{ broodstockNames[selectedBatch.broodstockStatus] }}{{ selectedBatch.broodstockLine ? ` · ${selectedBatch.broodstockLine}` : '' }}</dd></div><div><dt>Ngày sản xuất</dt><dd>{{ formatDate(selectedBatch.productionDate) }}</dd></div><div><dt>Thời điểm tiếp nhận</dt><dd>{{ formatDate(selectedBatch.receivedAt) }}</dd></div><div v-if="selectedBatch.healthCertificateUrl" class="detail-wide"><dt>Giấy chứng nhận kiểm dịch</dt><dd><img v-if="['jpg','jpeg','png','webp'].includes(selectedBatch.healthCertificateFormat)" class="media-preview" :src="selectedBatch.healthCertificateUrl" alt="Giấy chứng nhận kiểm dịch"><iframe v-else-if="selectedBatch.healthCertificateFormat === 'pdf'" class="document-preview" :src="selectedBatch.healthCertificateUrl" title="Giấy chứng nhận kiểm dịch PDF" /><a :href="selectedBatch.healthCertificateUrl" target="_blank" rel="noopener noreferrer">Mở giấy chứng nhận</a></dd></div><div class="detail-wide"><dt>Ghi chú</dt><dd>{{ selectedBatch.notes || 'Không có ghi chú' }}</dd></div></dl>
        <section class="batch-history-section"><div class="history-section-heading"><div><h3>Biến động số lượng</h3><p>Số lượng hiện tại: {{ formatQuantity(selectedBatch.currentEstimatedQuantity) }} con</p></div><v-btn v-if="['active','ready_for_sale'].includes(selectedBatch.status)" size="small" color="primary" variant="outlined" @click="openQuantityForm">Ghi biến động</v-btn></div>
          <v-progress-linear v-if="batchHistoryLoading" indeterminate color="primary" />
          <p v-else-if="!quantityEvents.length" class="history-empty">Chưa có sự kiện số lượng.</p>
          <div v-else class="history-list"><article v-for="event in quantityEvents" :key="event.id" class="history-row"><div><strong>{{ quantityEventNames[event.eventType] || event.eventType }}</strong><small>{{ formatTimestamp(event.occurredAt) }} · {{ event.reason || '—' }}</small><small v-if="event.adjustmentDirection">Điều chỉnh {{ event.adjustmentDirection === 'increase' ? 'tăng' : 'giảm' }}</small><small v-if="event.fromTank || event.toTank">Ao/bể: {{ event.fromTank?.code || '—' }}{{ event.toTank ? ` → ${event.toTank.code}` : '' }}</small><small>Người ghi: {{ event.creator?.displayName || 'Tài khoản hiện tại' }}</small><small v-if="event.notes">{{ event.notes }}</small></div><b :class="{ 'quantity-negative': quantityEventDelta(event) < 0, 'quantity-positive': quantityEventDelta(event) > 0 }">{{ quantityEventDelta(event) === null ? '±' : quantityEventDelta(event) > 0 ? '+' : '' }}{{ quantityEventDelta(event) === null ? formatQuantity(event.quantity) : formatQuantity(quantityEventDelta(event)) }}</b></article></div>
        </section>
        <section class="batch-history-section"><div class="history-section-heading"><div><h3>Mẫu tăng trưởng</h3><p>Cỡ mẫu, khối lượng, kích thước và sinh khối theo từng lần lấy mẫu.</p></div><v-btn v-if="['active','ready_for_sale'].includes(selectedBatch.status)" size="small" color="primary" variant="outlined" @click="growthForm = emptyGrowthForm(); growthDialog = true">Ghi mẫu</v-btn></div>
          <v-progress-linear v-if="batchHistoryLoading" indeterminate color="primary" />
          <p v-else-if="!growthSamples.length" class="history-empty">Chưa có mẫu tăng trưởng.</p>
          <div v-else class="history-list"><article v-for="sample in growthSamples" :key="sample.id" class="history-row growth-row"><div><strong>{{ formatTimestamp(sample.sampledAt) }} · {{ sample.method === 'ai' ? 'AI' : sample.method === 'combined' ? 'Kết hợp' : 'Thủ công' }}</strong><small>Cỡ mẫu {{ formatQuantity(sample.sampleCount) }} con<span v-if="sample.averageWeightG !== null"> · {{ sample.averageWeightG }} g/con</span><span v-if="sample.averageLengthMm !== null"> · dài TB {{ sample.averageLengthMm }} mm</span></small><small><span v-if="sample.lengthMinMm !== null && sample.lengthMaxMm !== null">Khoảng dài {{ sample.lengthMinMm }}–{{ sample.lengthMaxMm }} mm · </span><span v-if="sample.estimatedQuantity !== null">Ước tính {{ formatQuantity(sample.estimatedQuantity) }} con · </span><span v-if="sample.biomassKg !== null">Sinh khối {{ sample.biomassKg }} kg · </span><span v-if="sample.uniformityScore !== null">Đồng đều {{ sample.uniformityScore }}%</span></small><small>Người ghi: {{ sample.sampler?.displayName || 'Tài khoản hiện tại' }}</small><small v-if="sample.notes">{{ sample.notes }}</small></div></article></div>
        </section>
        <section class="batch-history-section"><div class="history-section-heading"><div><h3>Lịch sử kiểm tra chất lượng</h3><p>Kết quả kiểm tra và trạng thái xử lý.</p></div><v-btn size="small" variant="text" @click="openQualityHistory(selectedBatch)">Mở đầy đủ</v-btn></div><p v-if="!qualityChecks.length" class="history-empty">Chưa có lần kiểm tra chất lượng.</p><div v-else class="history-list"><article v-for="check in qualityChecks.slice(0, 5)" :key="check.id" class="history-row"><div><strong>{{ checkTypeOptions.find(option => option.value === check.checkType)?.title || check.checkType }}</strong><small>{{ formatTimestamp(check.checkedAt) }} · {{ resultNames[check.result] || check.result }} · {{ reviewNames[check.reviewStatus] || check.reviewStatus }}</small></div></article></div></section>
      </template><div class="dialog-actions"><v-btn variant="text" @click="detailDialog = false">Đóng</v-btn></div></v-card>
    </v-dialog>
<v-dialog v-model="quantityDialog" max-width="600"><v-card class="dialog-card"><span class="eyebrow">UC05.1.4 · BIẾN ĐỘNG SỐ LƯỢNG</span><h2>Ghi nhận biến động</h2><p class="detail-subtitle">{{ selectedBatch?.batchCode }} · hiện có {{ formatQuantity(selectedBatch?.currentEstimatedQuantity) }} con</p><div class="form-grid">
      <div><label>Loại biến động *</label><v-select v-model="quantityForm.eventType" :items="[{title:'Hao hụt / chết',value:'mortality'},...(canManage?[{title:'Điều chỉnh kiểm đếm',value:'adjustment'},{title:'Chuyển toàn bộ lô sang ao/bể khác',value:'transfer'}]:[])]" hide-details="auto" /></div>
      <div v-if="quantityForm.eventType === 'adjustment'"><label>Hướng điều chỉnh *</label><v-select v-model="quantityForm.adjustmentDirection" :items="[{title:'Tăng',value:'increase'},{title:'Giảm',value:'decrease'}]" hide-details="auto" /></div>
      <div><label>{{ quantityForm.eventType === 'transfer' ? 'Số lượng chuyển' : 'Số lượng biến động' }} *</label><v-text-field v-model="quantityForm.quantity" type="number" min="1" :readonly="quantityForm.eventType === 'transfer'" hide-details="auto" /></div>
      <div v-if="quantityForm.eventType === 'transfer'" class="span-2"><label>Ao/bể đích *</label><v-select v-model="quantityForm.targetTankId" :items="tanks.filter(tank => tank.id !== selectedBatch?.tankId)" :item-title="tank => `${tank.code} · ${tank.name}${tank.area?.name ? ` · ${tank.area.name}` : ''}`" item-value="id" hide-details="auto" /></div>
      <div><label>Thời điểm *</label><v-text-field v-model="quantityForm.occurredAt" type="datetime-local" hide-details="auto" /></div>
      <div class="span-2"><label>Lý do *</label><v-text-field v-model="quantityForm.reason" maxlength="1000" hide-details="auto" /></div>
      <div class="span-2"><label>Ghi chú</label><v-textarea v-model="quantityForm.notes" maxlength="4000" rows="2" auto-grow hide-details="auto" /></div>
    </div><div class="dialog-actions"><v-btn variant="text" @click="quantityDialog = false">Hủy</v-btn><v-btn color="primary" :loading="quantitySaving" @click="saveQuantityEvent">Lưu biến động</v-btn></div></v-card></v-dialog>
<v-dialog v-model="growthDialog" max-width="760" scrollable><v-card class="dialog-card"><span class="eyebrow">UC05.1.5 · MẪU TĂNG TRƯỞNG</span><h2>Ghi nhận mẫu</h2><p class="detail-subtitle">{{ selectedBatch?.batchCode }}</p><div class="form-grid">
      <div><label>Thời điểm lấy mẫu *</label><v-text-field v-model="growthForm.sampledAt" type="datetime-local" hide-details="auto" /></div><div><label>Phương pháp *</label><v-select v-model="growthForm.method" :items="[{title:'Thủ công',value:'manual'},{title:'AI',value:'ai'},{title:'Kết hợp',value:'combined'}]" hide-details="auto" /></div>
      <div><label>Cỡ mẫu (con) *</label><v-text-field v-model="growthForm.sampleCount" type="number" min="1" hide-details="auto" /></div><div><label>Số lượng lô ước tính</label><v-text-field v-model="growthForm.estimatedQuantity" type="number" min="0" hide-details="auto" /></div>
      <div><label>Tổng khối lượng mẫu (g)</label><v-text-field v-model="growthForm.totalSampleWeightG" type="number" min="0" step="any" hide-details="auto" /></div><div><label>Khối lượng TB (g/con)</label><v-text-field v-model="growthForm.averageWeightG" type="number" min="0" step="any" hide-details="auto" /></div>
      <div><label>Chiều dài TB (mm)</label><v-text-field v-model="growthForm.averageLengthMm" type="number" min="0" step="any" hide-details="auto" /></div><div><label>Chiều dài nhỏ nhất (mm)</label><v-text-field v-model="growthForm.lengthMinMm" type="number" min="0" step="any" hide-details="auto" /></div>
      <div><label>Chiều dài lớn nhất (mm)</label><v-text-field v-model="growthForm.lengthMaxMm" type="number" min="0" step="any" hide-details="auto" /></div><div><label>Sinh khối (kg)</label><v-text-field v-model="growthForm.biomassKg" type="number" min="0" step="any" hide-details="auto" /></div>
      <div><label>Độ đồng đều (0–100%)</label><v-text-field v-model="growthForm.uniformityScore" type="number" min="0" max="100" step="any" hide-details="auto" /></div><div class="span-2"><label>Ghi chú</label><v-textarea v-model="growthForm.notes" maxlength="4000" rows="2" auto-grow hide-details="auto" /></div>
    </div><p class="calculation-hint">Nếu chỉ nhập tổng khối lượng mẫu, hệ thống tự tính khối lượng trung bình. Nếu có khối lượng trung bình và số lượng ước tính, sinh khối được tính khi chưa nhập giá trị.</p><div class="dialog-actions"><v-btn variant="text" @click="growthDialog = false">Hủy</v-btn><v-btn color="primary" :loading="growthSaving" @click="saveGrowthSample">Lưu mẫu</v-btn></div></v-card></v-dialog>
</template>

<style scoped>
*{box-sizing:border-box}h1,h2,p{margin-top:0}h1{margin-bottom:9px;color:#134e4a;font-size:2.2rem}h2{margin-bottom:7px;color:#134e4a;font-size:1.25rem}.eyebrow{display:block;margin-bottom:8px;color:#087f6e;font-size:10px;font-weight:800;letter-spacing:.12em}.detail-subtitle{margin:0;color:#70817e;font-size:13px}table{width:100%;border-collapse:collapse;text-align:left}th{padding:13px 9px;color:#82908d;border-bottom:1px solid #e8eeec;font-size:9px;font-weight:800;letter-spacing:.04em;text-transform:uppercase;white-space:nowrap}td{padding:13px 9px;color:#687b77;border-bottom:1px solid #edf1f0;font-size:11px;vertical-align:middle}tbody tr:last-child td{border-bottom:0}td strong,td small{display:block}td strong{color:#214c46;font-size:11px}td small{margin-top:4px;color:#899693;font-size:10px}.status-action{padding:6px 8px;border:1px solid #bfdcd5;border-radius:6px;color:#087f6e;background:white;font-size:10px;cursor:pointer}.status-tag{display:inline-block;padding:5px 8px;border-radius:6px;background:#edf2f0;color:#65736f;font-size:9px;font-weight:750;white-space:nowrap}.status-active{background:#e0f3ed;color:#087f6e}.status-ready_for_sale{background:#fff2d4;color:#8a5a00}.status-sold{background:#e8efff;color:#3357a5}.status-failed,.status-cancelled{background:#fde9e7;color:#a33c34}.dialog-card{padding:26px!important;border-radius:10px!important}.dialog-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:18px}.detail-subtitle{margin-bottom:20px}.detail-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px;margin:20px 0 0}.detail-grid div{min-width:0}.detail-grid dt{margin-bottom:4px;color:#87938f;font-size:10px}.detail-grid dd{margin:0;color:#244b46;font-size:12px;overflow-wrap:anywhere}.detail-wide{grid-column:span 2}
.media-preview{display:block;max-width:100%;max-height:280px;margin-top:10px;border:1px solid #dce7e4;border-radius:7px;object-fit:contain}.document-preview{display:block;width:100%;height:320px;margin-top:10px;border:1px solid #dce7e4;border-radius:7px;background:#f7faf9}.detail-grid dd a{width:max-content;color:#087f6e;font-size:11px}
.batch-history-section{padding-top:18px;margin-top:20px;border-top:1px solid #e5ecea}.history-section-heading{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:10px}.history-section-heading h3{margin:0;color:#244b46;font-size:14px}.history-section-heading p,.history-empty{margin:4px 0 0;color:#788984;font-size:11px}.history-list{display:grid;gap:8px}.history-row{display:flex;align-items:flex-start;justify-content:space-between;gap:16px;padding:11px 12px;border:1px solid #e5ecea;border-radius:7px}.history-row strong,.history-row small{display:block}.history-row strong{color:#244b46;font-size:12px}.history-row small{margin-top:4px;color:#788984;font-size:10px;line-height:1.45}.history-row b{flex:0 0 auto;font-size:13px}.quantity-negative{color:#a33c34}.quantity-positive{color:#087f6e}
.status-processing{background:#e7f0ff;color:#315fa8}
@media(max-width:900px){th,td{padding-inline:8px}}
@media(max-width:600px){.detail-grid{grid-template-columns:1fr}.detail-wide{grid-column:auto}.dialog-card{padding:18px!important}}



*{box-sizing:border-box}h1,h2,p{margin-top:0}h1{margin-bottom:9px;color:#134e4a;font-size:2.2rem}h2{margin-bottom:7px;color:#134e4a;font-size:1.25rem}.eyebrow{display:block;margin-bottom:8px;color:#087f6e;font-size:10px;font-weight:800;letter-spacing:.12em}.detail-subtitle{margin:0;color:#70817e;font-size:13px}table{width:100%;border-collapse:collapse;text-align:left}th{padding:13px 9px;color:#82908d;border-bottom:1px solid #e8eeec;font-size:9px;font-weight:800;letter-spacing:.04em;text-transform:uppercase;white-space:nowrap}td{padding:13px 9px;color:#687b77;border-bottom:1px solid #edf1f0;font-size:11px;vertical-align:middle}tbody tr:last-child td{border-bottom:0}td strong,td small{display:block}td strong{color:#214c46;font-size:11px}td small{margin-top:4px;color:#899693;font-size:10px}.status-action{padding:6px 8px;border:1px solid #bfdcd5;border-radius:6px;color:#087f6e;background:white;font-size:10px;cursor:pointer}.status-tag{display:inline-block;padding:5px 8px;border-radius:6px;background:#edf2f0;color:#65736f;font-size:9px;font-weight:750;white-space:nowrap}.status-active{background:#e0f3ed;color:#087f6e}.status-ready_for_sale{background:#fff2d4;color:#8a5a00}.status-sold{background:#e8efff;color:#3357a5}.status-failed,.status-cancelled{background:#fde9e7;color:#a33c34}.dialog-card{padding:26px!important;border-radius:10px!important}.form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px 16px}.span-2{grid-column:span 2}.dialog-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:18px}.detail-subtitle{margin-bottom:20px}
.status-processing{background:#e7f0ff;color:#315fa8}
@media(max-width:900px){th,td{padding-inline:8px}}
@media(max-width:600px){.form-grid{grid-template-columns:1fr}.span-2{grid-column:auto}.dialog-card{padding:18px!important}}


*{box-sizing:border-box}h1,h2,p{margin-top:0}h1{margin-bottom:9px;color:#134e4a;font-size:2.2rem}h2{margin-bottom:7px;color:#134e4a;font-size:1.25rem}.eyebrow{display:block;margin-bottom:8px;color:#087f6e;font-size:10px;font-weight:800;letter-spacing:.12em}.detail-subtitle{margin:0;color:#70817e;font-size:13px}table{width:100%;border-collapse:collapse;text-align:left}th{padding:13px 9px;color:#82908d;border-bottom:1px solid #e8eeec;font-size:9px;font-weight:800;letter-spacing:.04em;text-transform:uppercase;white-space:nowrap}td{padding:13px 9px;color:#687b77;border-bottom:1px solid #edf1f0;font-size:11px;vertical-align:middle}tbody tr:last-child td{border-bottom:0}td strong,td small{display:block}td strong{color:#214c46;font-size:11px}td small{margin-top:4px;color:#899693;font-size:10px}.status-action{padding:6px 8px;border:1px solid #bfdcd5;border-radius:6px;color:#087f6e;background:white;font-size:10px;cursor:pointer}.status-tag{display:inline-block;padding:5px 8px;border-radius:6px;background:#edf2f0;color:#65736f;font-size:9px;font-weight:750;white-space:nowrap}.status-active{background:#e0f3ed;color:#087f6e}.status-ready_for_sale{background:#fff2d4;color:#8a5a00}.status-sold{background:#e8efff;color:#3357a5}.status-failed,.status-cancelled{background:#fde9e7;color:#a33c34}.dialog-card{padding:26px!important;border-radius:10px!important}.form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px 16px}.span-2{grid-column:span 2}.dialog-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:18px}.detail-subtitle{margin-bottom:20px}.calculation-hint{margin:12px 0 0;color:#71817d;font-size:11px;line-height:1.5}
.status-processing{background:#e7f0ff;color:#315fa8}
@media(max-width:900px){th,td{padding-inline:8px}}
@media(max-width:600px){.form-grid{grid-template-columns:1fr}.span-2{grid-column:auto}.dialog-card{padding:18px!important}}
</style>
